#!/usr/bin/env ruby

'''
- Fabiana Acosta; 10-10005
- Gianni Manilia; 12-10903
'''

require_relative 'retina_parser'

def main
	# Verificar extension
	ARGV[0] =~ /\w+\.rtn/
	if $&.nil?; puts "Unknown file extension"; return; end
		begin
		input = File::read(ARGV[0])
	rescue
		puts "File not found"
		return
	end
	# Crear lexer
	lexer = Lexer.new input
	# Obtener tokens hasta que se termine el input
	begin
		while lexer.catch_lexeme; end
		begin
			lexer = Lexer.new input
			parser = Parser.new
			ast = parser.parse lexer
			ast.print_ast
		rescue SyntacticError => e
			puts e
			return
		end

	# Tomar el primer error lexicografico
	rescue LexicographicError => e
		puts e
		return

	end
end

main